config/routes.rb
Rails.application.routes.draw do
  resources :expenses
  resources :budgets
  resources :incomes, only: %i[ new create show edit update ]
  get 'dashboard/index'
  get 'home/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "home#index"
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :user
  has_many :expenses, dependent: :destroy

  validates :category, presence: true
  validates :amount, presence: true
  validates :time_period, presence: true
  
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_budget, only: %i[ show edit update destroy ]

  # GET /budgets or /budgets.json
  def index
    @budgets = current_user.budgets
  end

  # GET /budgets/1 or /budgets/1.json
  def show
  end

  # GET /budgets/new
  def new
    @budget = current_user.budgets.build
  end

  # GET /budgets/1/edit
  def edit
  end

  # POST /budgets or /budgets.json
  def create
    @budget = current_user.budgets.build(budget_params)

    respond_to do |format|
      if @budget.save
        format.html { redirect_to budget_url(@budget), notice: "Budget was successfully created." }
        format.json { render :show, status: :created, location: @budget }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budgets/1 or /budgets/1.json
  def update
    respond_to do |format|
      if @budget.update(budget_params)
        format.html { redirect_to budget_url(@budget), notice: "Budget was successfully updated." }
        format.json { render :show, status: :ok, location: @budget }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budgets/1 or /budgets/1.json
  def destroy
    @budget.destroy

    respond_to do |format|
      format.html { redirect_to budgets_url, notice: "Budget was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budget
      @budget = Budget.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def budget_params
      params.require(:budget).permit(:user_id, :category, :amount, :time_period)
    end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/views/budgets/_budget.html.erb
<div id="<%= dom_id budget %>">
    <p>
    <strong>Category:</strong>
    <%= budget.category %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= number_to_currency( budget.amount) %>
  </p>

  <p>
    <strong>Time period:</strong>
    <%= budget.time_period %>
  </p>

</div>

app/views/budgets/_form.html.erb
<%= form_with(model: budget) do |form| %>
  <% if budget.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(budget.errors.count, "error") %>
        prohibited this budget from being saved:</h2>

      <ul>
        <% budget.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.text_field :category %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= (form.text_field :amount) %>
  </div>

  <div>
    <%= form.label :time_period, style: "display: block" %>
    <%= form.text_field :time_period %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/budgets/edit.html.erb
<h1>Editing budget</h1>

<%= render "form", budget: @budget %>

<br>

<div>
  <%= link_to "Show this budget", @budget %> |
  <%= link_to "Back to budgets", budgets_path %>
</div>

app/views/budgets/index.html.erb
<h1>Budgets</h1>

<div id="budgets">
  <% @budgets.each do |budget| %>
    <%= render budget %>
    <p>
      <%= link_to "Show this budget", budget %>
    </p>
  <% end %>
</div>

<%= link_to "New budget", new_budget_path %>

app/views/budgets/new.html.erb
<h1>New budget</h1>

<%= render "form", budget: @budget %>

<br>

<div>
  <%= link_to "Back to budgets", budgets_path %>
</div>

app/views/budgets/show.html.erb
<%= render @budget %>

<div>
  <%= link_to "Edit this budget", edit_budget_path(@budget) %> |
  <%= link_to "Back to budgets", budgets_path %>

  <%= button_to "Destroy this budget", @budget, method: :delete %>
</div>