config/routes.rb
Rails.application.routes.draw do
  resources :expenses
  resources :budgets
  resources :incomes, only: %i[ new create show edit update ]
  get 'dashboard/index'
  get 'home/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "home#index"
end

app/models/income.rb
class Income < ApplicationRecord
  belongs_to :user
  validates :amount, presence: true, numericality: { greater_than: 10 }
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController

    before_action :authenticate_user!
    before_action :set_income, only: %i[ show edit update ]
    
    # GET /incomes/1 or /incomes/1.json
    def show
    end
  
    # GET /incomes/new
    def new
      @income = current_user.build_income
    end
  
    # GET /incomes/1/edit
    def edit
    end
  
    # POST /incomes or /incomes.json
    def create
      @income = current_user.build_income(income_params)
  
      respond_to do |format|
        if @income.save
          format.html { redirect_to expenses_path(@expenses), notice: "Income was successfully created." }
          format.json { render :show, status: :created, location: @income }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @income.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /incomes/1 or /incomes/1.json
    def update
      respond_to do |format|
        if @income.update(income_params)
          format.html { redirect_to expenses_path(@expenses), notice: "Income was successfully updated." }
          format.json { render :show, status: :ok, location: @income }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @income.errors, status: :unprocessable_entity }
        end
      end
    end
  
      
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_income
        @income = Income.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def income_params
        params.require(:income).permit(:user_id, :amount)
      end
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/incomes/_form.html.erb
<%= form_with(model: income, class: "needs-validation", novalidate: true) do |form| %>
  <div class="mb-4">
    <% if income.errors.any? %>
      <div class="alert alert-danger">
        <h4 class="alert-heading">Errors prohibited this income from being saved:</h4>
        <ul>
          <% income.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>

  <div class="mb-3">
    <%= form.label :amount, class: "form-label" %>
    <%= form.text_field :amount, class: "form-control", placeholder: "Enter income amount", required: true %>
    <div class="invalid-feedback">
      Please enter a valid income amount.
    </div>
  </div>

  <div class="mb-3">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/incomes/_income.html.erb
<div id="<%= dom_id income %>">
  <p>
    <strong>Amount:</strong>
    <%= income.amount %>
  </p>

</div>

app/views/incomes/edit.html.erb
<h1>Editing income</h1>

<%= render "form", income: @income %>

<br>

app/views/incomes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Incomes</h1>

<div id="incomes">
  <% @incomes.each do |income| %>
    <%= render income %>
    <p>
      <%= link_to "Show this income", income %>
    </p>
  <% end %>
</div>

<%= link_to "New income", new_income_path %>

app/views/incomes/new.html.erb
<h1>New income</h1>

<%= render "form", income: @income %>

<br>

<div>
  <%= link_to "Back to incomes", incomes_path %>
</div>

app/views/incomes/show.html.erb
<%= render @income %>

<div>
  <%= link_to "Edit this income", edit_income_path(@income) %> |
  <%= link_to "Back to incomes", incomes_path %>

  <%= button_to "Destroy this income", @income, method: :delete %>
</div>