config/routes.rb
Rails.application.routes.draw do
  resources :expenses
  resources :budgets
  resources :incomes, only: %i[ new create show edit update ]
  get 'dashboard/index'
  get 'home/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "home#index"
end

app/views/layouts/navigation/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
  <div class="container-fluid">
    <%= link_to "SavvySpend", root_path, class: "navbar-brand logo" %>
    <% if current_user.income.present? && current_user.income.persisted? %>
      <%= link_to "Dashboard", dashboard_index_path, class: "navbar-brand", "aria-current": "page" %>
      <% end %>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "@#{current_user.username}", edit_user_registration_path, class: "nav-link active username", "aria-current": "page" %>
        </li>
        <% if current_user.income.present? && current_user.income.persisted? %>
        <li> <%= link_to "$#{current_user.user_income}", edit_income_path(current_user.income), class: "nav-link active income", "aria-current": "page" %></li>
        <li><%= link_to "My Budgets", budgets_path(@Budgets), class: "nav-link active", "aria-current": "page"  %></li>
        <li><%= link_to "My Expenses", expenses_path(@Expenses), class: "nav-link active", "aria-current": "page"  %></li>
        <% else %>
        <%= link_to "Please Enter Income to continue", new_income_path, class: "nav-link active no-income", "aria-current": "page" %>
        <% end %>
          <%= form_with(url: destroy_user_session_path, method: :delete) do |form| %>
            <li class="nav-item"><%= form.submit "Sign Out", class: "nav-link active", "aria-current": "page" %></li>
          <% end %>
        <% else %>
          <li class="nav-item"><%= link_to "Sign In",
            new_user_session_path,
            class: "nav-link active",
            "aria-current": "page" %></li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>